name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      test-command: |
        nimble list --installed --version
        env NIMLANG=c nimble --useSystemNim test
        env NIMLANG=cpp nimble --useSystemNim test
        env nimble --useSystemNim examples
